### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by zhostasa** [dessalines/simple-vote#72]
While attempting to initialize app via docker build I ran into following problem, which I believe prevents Frontend from starting up. Being primarily Backend developer I am unable to analyze it further.

$ ts-node git.version.ts
git error: Error: Command failed: git describe --abbrev=0 --tags
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git

git error: Error: Command failed: git rev-parse --abbrev-ref HEAD
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git

git error: Error: Command failed: git rev-parse --short HEAD
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git

version: '1.1.2', revision: '', branch: '', tag: ''
$ ng build --prod --aot
 10% building modules 3/3 modules 0 activeWarning: Can't resolve all parameters for NG2WebSocket in /opt/simple-vote/ui/src/app/services/ng2-websocket.ts: (?, ?, ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for NG2WebSocket in /opt/simple-vote/ui/src/app/services/ng2-websocket.ts: (?, ?, ?). This will become an error in An 10% building modules 3/4 modules 1 active …4-3!/opt/simple-vote/ui/src/styles.scssWarning: Can't resolve all parameters for NG2WebSocket in /opt/simple-vote/ui/src/app/services/ng2-websocket.ts: (?, ?, ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for NG2WebSocket in /opt/simple-vote/ui/src/app/services/ng2-websocket.ts: (                                                                                   Date: 2018-10-29T19:34:18.473Z
Hash: 35ee50ef40984034503f
Time: 124979ms

**Comment by dessalines** [comment]
Those are just warnings, it got to the build step, and it continued.

**Comment by zhostasa** [comment]
True enough the build finished and application started. I verified that Java backend is up and servicing requests, but I am unable to access frontend. These are only log entries that I found which might point to any problem.

**Comment by dessalines** [comment]
http://localhost:4567 . Whats the error on the front end?

**Comment by zhostasa** [comment]
When attempting wget locally I get 404, when attempting connection from remote machine I receive "ERR_CONTENT_DECODING_FAILED" -> http://194.182.72.244:4567/

**Comment by dessalines** [comment]
Damn this isn't the first time I've seen this error. Let me take a look. Docker is suppose to abstract these things. Can I ask what machine you're running this on?

**Comment by zhostasa** [comment]
ubuntu 16.04 LTS

**Comment by dessalines** [comment]
Okay, I'm gonna install virtualbox and your exact version of ubuntu and try to figure this one out.

**Comment by dessalines** [comment]
I've finally been able to replicate the problem, I should have a fix for this soon.

**Comment by AdrianAcala** [comment]
@dessalines , I also had a similar problem. It seems like it has something to do with gzip. 

[JDK Bug](https://bugs.java.com/view_bug.do?bug_id=JDK-8189789)

**Comment by dessalines** [comment]
Okay I think I fixed this now. Run

```
git pull
docker-compose up --build
```

**Comment by AdrianAcala** [comment]
@dessalines , still not working. I deleted all my images just to make sure and rebuild and still no dice.

**Comment by dessalines** [comment]
God I hate docker. The whole point is to abstract the OS from problems. And here I am running it one OS fine, the other has problems. Now I fix it for both, and OTHER os's still have problems... ugh. Lemme do some more testing, but this is really difficult if I can't replicate the problem.

**Comment by dessalines** [comment]
Okay I think I got it. Run the above commands again, make sure it pulled the new changes.

**Comment by zhostasa** [comment]
I ran the whole build on the latest version and sadly, no joy.
If you provide me a contact (I suggest https://temp-mail.org) I can send you credentials.

**Comment by dessalines** [comment]
zocewujumo@pachilly.com

**Comment by dessalines** [comment]
Okay this is fixed now. http://194.182.72.244:4567 is working

It ended up being that the docker `COPY` command runs different on different systems. Yeah, wow. 

Its already running, but if you want, you can run
```
docker-compose build --no-cache
docker-compose-up
```

**Comment by zhostasa** [comment]
Yeah, docker is...tricky sometimes. Thank you

**Comment by dessalines** [comment]
No prob, sorry about this.
